apiVersion: v1
kind: Service
metadata:
  name: kvstore
  labels:
    app: kvstore
spec:
  # type: NodePort
  clusterIP: None
  ports:
  - port: 46656
    name: p2p
  - port: 46657
    name: rpc
  selector:
    app: tm
