version: '2.0'

services:

  tm_node1: &node
    image: tendermint/tendermint
    container_name: tm_node1
    hostname: tm_node1
    tty: true
    ports:
      - '46667:46657'
    volumes:
      - ./node1_data:/tendermint
    entrypoint: ["bash", "-c", "tendermint node --p2p.persistent_peers=5693b6f9cb2435a5c89ab684904e7305fa2e1f1a@tm_node1:46656,a61b9cc203dd93e4b4b6b23e443d61b39156292a@tm_node2:46656,64866575ec135272df0fd2f542b51306482a7c9e@tm_node3:46656,1879dace49dccc07d988183f8df14fa8ce728bb3@tm_node4:46656 --moniker=`hostname` --proxy_app=persistent_kvstore --consensus.create_empty_blocks=false"]

  tm_node2:
    <<: *node
    container_name: tm_node2
    hostname: tm_node2
    ports:
      - '46668:46657'
    volumes:
      - ./node2_data:/tendermint

  tm_node3:
    <<: *node
    container_name: tm_node3
    hostname: tm_node3
    ports:
      - '46669:46657'
    volumes:
      - ./node3_data:/tendermint

  tm_node4:
    <<: *node
    container_name: tm_node4
    hostname: tm_node4
    ports:
      - '46660:46657'
    volumes:
      - ./node4_data:/tendermint
