version: '2.0'

services:

  tm_node1: &node
    image: tendermint/tendermint:0.17.1
    container_name: tm_node1
    hostname: tm_node1
    tty: true
    ports:
      - '46667:46657'
    volumes:
      - ./node1_data:/tendermint
    entrypoint: ["sh", "-c", "tendermint node --p2p.persistent_peers=f6e4c91a17c79b4805592603204ada8895196205@tm_node1:46656,f6859a0b40dfd2d21ae7b0f9a5796e7b62ac4ca4@tm_node2:46656,0fab048217e63e240b7eade1ed642906660bb0fa@tm_node3:46656,ccc8005a4e2a4022e79b84c946aa05b4e056a9b0@tm_node4:46656 --moniker=`hostname` --proxy_app=persistent_kvstore --consensus.create_empty_blocks=false"]

  tm_node2:
    <<: *node
    container_name: tm_node2
    hostname: tm_node2
    ports:
      - '46668:46657'
    volumes:
      - ./node2_data:/tendermint

  tm_node3:
    <<: *node
    container_name: tm_node3
    hostname: tm_node3
    ports:
      - '46669:46657'
    volumes:
      - ./node3_data:/tendermint

  tm_node4:
    <<: *node
    container_name: tm_node4
    hostname: tm_node4
    ports:
      - '46660:46657'
    volumes:
      - ./node4_data:/tendermint
