version: '2.0'

services:

  tm_node1:
    image: tendermint/tendermint
    container_name: tm_node1
    hostname: tm_node1
    tty: true
    ports:
      - '46667:46657'
    volumes:
      - ./node1_data:/tendermint
    entrypoint: ["bash", "-c", "tendermint node --p2p.persistent_peers=d902b83f46131a80a82df2198a704889c5833284@tm_node2:46656 --moniker=`hostname` --proxy_app=kvstore --consensus.create_empty_blocks=false"]

  tm_node2:
    image: tendermint/tendermint
    container_name: tm_node2
    hostname: tm_node2
    tty: true
    ports:
      - '46668:46657'
    volumes:
      - ./node2_data:/tendermint
    entrypoint: ["bash", "-c", "tendermint node --p2p.persistent_peers=59ef92d5c6a408a59e4a1d599a8aff0d4ef37785@tm_node1:46656 --moniker=`hostname` --proxy_app=kvstore --consensus.create_empty_blocks=false"]
